version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/ypf-tienda

    steps:
      # descargar el repositorio o la rama usada en la pull request a la ruta
      # configurada en `working_directory`
      - checkout

      # restaurar las dependencias desde la cache
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}

      # instalar las dependencias
      - run:
          name: Instalar las dependencias
          command: cd client && npm install

      # guardar las dependencias en la cache
      - save_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - client/node_modules

      # ejecutar el linter
      - run:
          name: Ejecutar el linter
          command: cd client && npm run lint

      # ejecutar los tests unitarios
      - run:
          name: Ejecutar los tests unitarios
          command: cd client && npm run test:unit
